### ISSUE TITLE
Stop Button missing

### ISSUE THREAD

**Issue by itapower** [mapero/esphome-hcpbridge#2]
Hello,
I have installed the firmware on a ESP32S3 for a Hörmann Garage with SupraMatic E4. Everything is working fine in Home Assistant. What I miss is the stop button. Also the call sevice to stop the cover is missing. Any suggestion why this is not available?
![garage](https://github.com/mapero/esphome-hcpbridge/assets/80904290/f9965fa3-9ed6-462c-afa7-6baecaedd691)

**Comment by mapero** [comment]
Hi @itapower, 

Thanks for the feedback. Can you provide the esphome configuration (without sensible data)?

I will have a look at it and check with the latest esphome version.

**Comment by itapower** [comment]
Hi mapero,
thank you for your quick reply.
Attached the configuration.
esphome:
  name: garage-tor-links
  friendly_name: Garage Tor links
  libraries:
    - emelianov/modbus-esp8266
  platformio_options:
    board_build.f_cpu: 240000000L
    board_build.flash_mode: qio
    monitor_speed: 9600
    monitor_filters: esp32_exception_decoder
    lib_ldf_mode: deep+
    # board_build.f_flash: 40000000L

external_components:
    source: github://mapero/esphome-hcpbridge
    refresh: 0s

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: ""
  password: ""
  manual_ip:
    static_ip: 192.168.178.8
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

hcpbridge:
  is_connected:
    name: "HCPBridge Connected"
  rx_pin: 18 # optional, default=18
  tx_pin: 17 # optional, default=17

cover:
  - platform: hcpbridge
    name: Garage Door

switch:
  - platform: hcpbridge
    name: Garage Tor links Light

binary_sensor:
# Reports when the reed switch from GPIO05 to GND is sensing a magnet and the door is closed.
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: False
    name: Garage links Kontakt
    device_class: garage_door

sensor:
  - platform: ultrasonic
    trigger_pin: 
      number: 6
    echo_pin: 
      number: 7
    name: "Garage links Distanz"
    timeout: 3m

**Comment by mapero** [comment]
Thanks. Found the issue. There is a new flag which indicates that the component supports stop:
https://github.com/esphome/esphome/blob/4cc17dac0dff22ef476aa7b98abf17b675749379/esphome/components/cover/cover_traits.h#L19

I will fix this today or tomorrow and provide a new version.

**Comment by itapower** [comment]
Great. Thank you very much
